
version: "3.1"

services:
  # php:
  #   build: .
  #   ports:
  #     - "8000:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www/html
  #   links:
  #     - db
  #  db:
  #    image: mysql:5.7
  #    volumes:
  #      - ./docker/data_db:/var/lib/mysql
  #    ports:
  #      - "3306:3306"  
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=keyon
  db:
     image: postgres
     volumes:
      - ./pgsql:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_PASSWORD=123456
       - POSTGRES_USER=sistemaFinanceiro
       - POSTGRES_DB=sistemaFinanceiro


